In [21]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt


import pandas as pd

In [22]:
#NBA 全聯盟戰績
df_temp = pd.read_html('https://s5.sir.sportradar.com/taiwansportslottery/zht/3/season/72821')
len(df_temp)

2

In [23]:
df = df_temp[0]
df

,位置#,球隊隊伍,勝,負,勝率,勝差,淘汰數字,外卡勝差,近10場戰績,近期連勝敗,淨勝球(分),主,客
0,1,亞歷桑那響尾蛇亞歷桑那響尾蛇,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
1,1,亞特蘭大勇士亞特蘭大勇士,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
2,1,巴爾地摩金鶯巴爾地摩金鶯,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
3,1,波士頓紅襪波士頓紅襪,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
4,1,芝加哥小熊芝加哥小熊,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
5,1,芝加哥白襪芝加哥白襪,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
6,1,辛辛那堤紅人辛辛那堤紅人,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
7,1,克里夫蘭印地安人克里夫蘭印地安人,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
8,1,科羅拉多落磯山科羅拉多落磯山,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
9,1,底特律老虎底特律老虎,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
10,1,休士頓太空人休士頓太空人,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
11,1,堪薩斯皇家堪薩斯皇家,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
12,1,洛杉磯天使洛杉磯天使,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
13,1,洛杉磯道奇洛杉磯道奇,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
14,1,邁阿密馬林魚邁阿密馬林魚,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
15,1,密爾瓦基釀酒人密爾瓦基釀酒人,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
16,1,明尼蘇達雙城明尼蘇達雙城,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
17,1,紐約大都會紐約大都會,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
18,1,紐約洋基紐約洋基,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
19,1,奧克蘭運動家奧克蘭運動家,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
20,1,費城費城人費城費城人,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
21,1,匹茲堡海盜匹茲堡海盜,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
22,1,聖地牙哥教士聖地牙哥教士,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
23,1,舊金山巨人舊金山巨人,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
24,1,西雅圖水手西雅圖水手,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
25,1,聖路易紅雀聖路易紅雀,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
26,1,坦帕灣光芒坦帕灣光芒,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
27,1,德州遊騎兵德州遊騎兵,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
28,1,多倫多藍鳥多倫多藍鳥,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0
29,1,華盛頓國民華盛頓國民,0,0,0,-,-,0.0,0-0,-,0,0-0,0-0

In [24]:
df_temp = pd.read_html('https://s5.sir.sportradar.com/taiwansportslottery/zht/3/season/72821/fixtures')
len(df_temp)

1

In [25]:
 df_temp[0]

    Unnamed: 0              Unnamed: 1
0      三月 2020                 三月 2020
1   2020/03/27                     NaN
2        01:10     華盛頓國民華盛頓國-紐約大都會紐約大都
3        01:10  底特律老虎底特律老-克里夫蘭印地安人克里夫蘭
4        02:10     堪薩斯皇家堪薩斯皇-芝加哥白襪芝加哥白
..         ...                     ...
69       10:10   科羅拉多落磯山科羅拉多-洛杉磯道奇洛杉磯道
70       10:10    明尼蘇達雙城明尼蘇達-西雅圖水手西雅圖水
71       10:10   亞特蘭大勇士亞特蘭大-聖地牙哥教士聖地牙哥
72  2020/04/01                     NaN
73       04:05     洛杉磯天使洛杉磯天-德州遊騎兵德州遊騎

[74 rows x 2 columns]

In [26]:
df = df_temp[0]
column_name = df.loc[0, :]
df.columns = column_name
df
df.drop(0, inplace=True)
df.dropna(axis=1, how='all')

0      三月 2020                 三月 2020
1   2020/03/27                     NaN
2        01:10     華盛頓國民華盛頓國-紐約大都會紐約大都
3        01:10  底特律老虎底特律老-克里夫蘭印地安人克里夫蘭
4        02:10     堪薩斯皇家堪薩斯皇-芝加哥白襪芝加哥白
5        02:10   芝加哥小熊芝加哥小-密爾瓦基釀酒人密爾瓦基
..         ...                     ...
69       10:10   科羅拉多落磯山科羅拉多-洛杉磯道奇洛杉磯道
70       10:10    明尼蘇達雙城明尼蘇達-西雅圖水手西雅圖水
71       10:10   亞特蘭大勇士亞特蘭大-聖地牙哥教士聖地牙哥
72  2020/04/01                     NaN
73       04:05     洛杉磯天使洛杉磯天-德州遊騎兵德州遊騎

[73 rows x 2 columns]